### PR TITLE
feat(editor-config):added editor config file

### PR DESCRIPTION
**Pull request by extrasad**
@CharlyJazz Check the rules

### CODE REVIEW

**Comment by extrasad** [comment]
#4

**Comment by CharlyJazz** [comment]
Can you investigate if the current configuration is right for Python? Because we can make one configuration for Javascript and another for python

**Review by CharlyJazz — COMMENTED** [review]
Can you investigate if the current configuration is right for Python? Because we can make one configuration for Javascript and another for python

**Comment by extrasad** [comment]
Aright, ill work on that

**Pull request merged**
